# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    tags:
      "v*"

permissions: write-all

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build with pyinstaller
      run: |
        pyinstaller -Fw gpt_test.py
      working-directory: ./src/Cyber Project 2D/Python
    - name: Package 
      run: |
        tar -a -c -f Windows.zip -C ./dist/ gpt_test.exe
      working-directory: ./src/Cyber Project 2D/Python  
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        prerelease: true
        files: |
          Windows.zip
